# Data preparation for P2
Using the original data and preparing it so that only the data needed for the analysis for the survey analysis paper is left.

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)

In [2]:
NL_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Study_new_respondents_Wave_Five_NL.csv')
UK_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Study_new_respondents_Wave_Five_UK.csv')
US_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Five_US.csv')
ID_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Five_ID.csv')

NL_data_w5.head()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q29h_com_what_other_p3,Q35_responsibility_citizens,Q35_responsibility_business,Q35_responsibility_ngo_local,Q35_responsibility_ngo_international,Q35_responsibility_gov_local,Q35_responsibility_gov_national,Q35_responsibility_w_authorities,Q35_responsibility_other,Q0_education_NL
0,0,4,5,2,900000,2300,2022,4,3,3,...,NaN,0,0,0,0,50,25,25,0,5
1,1,2,5,2,600000,1200,1992,4,3,4,...,NaN,0,0,0,0,0,0,0,100,5
2,2,2,2,2,170000,900,2010,3,2,3,...,NaN,0,0,0,0,0,50,50,0,4
3,3,2,2,1,,1000,2021,2,4,1,...,NaN,0,0,0,0,0,50,50,0,6
4,4,97,4,2,350000,1500,2014,4,4,3,...,NaN,0,0,0,0,0,0,0,100,7

In [3]:
NL_data_w5 = NL_data_w5.replace(' ', np.NaN)
NL_data_w5 = NL_data_w5.replace('', np.NaN)
NL_data_w5 = NL_data_w5.apply(pd.to_numeric, errors='ignore')

UK_data_w5 = UK_data_w5.replace(' ', np.NaN)
UK_data_w5 = UK_data_w5.replace('', np.NaN)
UK_data_w5 = UK_data_w5.apply(pd.to_numeric, errors='ignore')

US_data_w5 = US_data_w5.replace(' ', np.NaN)
US_data_w5 = US_data_w5.replace('', np.NaN)
US_data_w5 = US_data_w5.apply(pd.to_numeric, errors='ignore')

ID_data_w5 = ID_data_w5.replace(' ', np.NaN)
ID_data_w5 = ID_data_w5.replace('', np.NaN)
ID_data_w5 = ID_data_w5.apply(pd.to_numeric, errors='ignore')

In [4]:
print('NL: ', NL_data_w5.shape)
print('UK: ', UK_data_w5.shape)
print('US: ', US_data_w5.shape)
print('ID: ', ID_data_w5.shape)

NL:  (420, 311)
UK:  (743, 320)
US:  (448, 218)
ID:  (341, 338)

Rules to remove [1]:

Respondents that said they talked to more than 100 people about flooding related issues (Q27_fl_convo_people > 100).
Respondents that had more than 200 conversations around the topic of flooding in the last year (Q25_fl_convo_times > 200). --> This removes 2 respondents in the UK and NL, and 1 in ID.
1. After checking just the social influence data (Discussion with Tatiana 21.03.2024) - potentially to be extended when checking policy responses.

In [5]:
NL_data_w5 = NL_data_w5.drop(NL_data_w5[NL_data_w5.Q27_fl_convo_people > 100].index)
NL_data_w5 = NL_data_w5.drop(NL_data_w5[NL_data_w5.Q25_fl_convo_times > 200].index)
NL_data_w5['country'] = 'NL'

UK_data_w5 = UK_data_w5.drop(UK_data_w5[UK_data_w5.Q27_fl_convo_people > 100].index)
UK_data_w5 = UK_data_w5.drop(UK_data_w5[UK_data_w5.Q25_fl_convo_times > 200].index)
UK_data_w5['country'] = 'UK'

US_data_w5 = US_data_w5.drop(US_data_w5[US_data_w5.Q27_fl_convo_people > 100].index)
US_data_w5 = US_data_w5.drop(US_data_w5[US_data_w5.Q25_fl_convo_times > 200].index)
US_data_w5['country'] = 'US'

ID_data_w5 = ID_data_w5.drop(ID_data_w5[ID_data_w5.Q27_fl_convo_people > 100].index)
ID_data_w5 = ID_data_w5.drop(ID_data_w5[ID_data_w5.Q25_fl_convo_times > 200].index)
ID_data_w5['country'] = 'ID'

In [6]:
print('NL: ', NL_data_w5.shape)
print('UK: ', UK_data_w5.shape)
print('US: ', US_data_w5.shape)
print('ID: ', ID_data_w5.shape)

NL:  (418, 312)
UK:  (741, 321)
US:  (448, 219)
ID:  (340, 339)

In [7]:
data_w5 = pd.concat([NL_data_w5, UK_data_w5, ID_data_w5, US_data_w5], ignore_index = True)
data_w5.head()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q29h_com_what_cause_p7,Q29h_com_what_measures_p7,Q29h_com_what_community_p7,Q29h_com_what_gov_react_p7,Q29h_com_what_gov_adapt_p7,Q29h_com_what_livability_p7,Q29h_com_what_other_p4,Q29h_com_what_other_p5,Q29h_com_what_other_p6,Q29h_com_what_other_p7
0,0,4.0,5.0,2.0,900000.0,2300.0,2022.0,4.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,5.0,2.0,600000.0,1200.0,1992.0,4.0,3.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,2.0,2.0,170000.0,900.0,2010.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2.0,2.0,1.0,NaN,1000.0,2021.0,2.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,97.0,4.0,2.0,350000.0,1500.0,2014.0,4.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Aligning response categories for variables and counting occurrences

The grouping of the data across multiple waves concerns the variables 
- gender,
- level of education,
- income quintile,
- age,
- flood experience.

To align the data across the different waves and countries, the following is done:

##### Gender
- We connect the data on gender from the first wave (US, ID) to the data from the fifth wave.
##### Level of Education
- We connect the data on gender from the first wave (US, ID) to the data from the fifth wave. 
- Different education categories are used across the different countries. To unify, we group all categories into the following four categories:
    - no high school degree. For the different countries this includes:
        - ID: primary school (SD)
        - NL: I did not complete any formal education, primary education, lower secondary education
        - UK: no formal qualifications, youth training certificate / skill seekers
        - US: no highschool
    - high school degree. For the different countries this includes:
        - ID: junior secondary school (SMP), secondary school (SMA), vocational and pre-professional senior secondary schools (SMK)
        - NL: lower or upper secondary education
        - UK: recognized trade apprenticeship, clerical and commercial, City&Guilds certificate, ONC, CSE grades 2-5, CSE grade 1, GCE 0 level, GCSE, school certificate, Scottish ordinary/lower certificate, GCE A level or Higher certificate
        - US: high school graduate, some college
    - college degree. For the different countries this includes:
        - ID: Vocational education D3 level, Level S-1 (e.g., BA, B.Sc., B.Ed.)
        - NL: post-secondary, non-tertiary education, short-cycle tertiary education (vocational training), Bachelors or equivalent level degree
        - UK: University diploma, University or CNAA first degree (e.g., BA, B.Sc., B.Ed.), City&Guilds certificate - advances, Nursing qualification, Teaching qualification, 
        - US: 2-year, 4-year college program
    - post graduate degree. For the different countries this includes:
        - ID: Level S-2/S-3 (Masters, Doctorate), professional higher education
        - NL: Masters or equivalent level degree, Doctoral or equivalent level degree
        - UK: University or CNAA higher degree (e.g., MSc, PhD), other technical, professional or higher qualification
        - US: post-grad
#### Income quintile
- We connect the data on gender from the first wave (US, ID) to the data from the fifth wave.
- The assumption is that respondents stayed in their income quintile between the first and fifth wave (concerning US, ID).
- For ID, respondents gave their income in IDR. We translated this into income quintiles using data from the worldbank (https://pip.worldbank.org/country-profiles/IDN):
    - lowest quintile: < 19.4 million IDR
    - second-lowest quintile: 19.4-26.6 million IDR
    - middle quintile: 26.6-35.8 million IDR
    - second highest quintile: 35.8-51.1 million IDR
    - highest quintile: > 51.1 million IDR
#### Age
- We connect the data on gender from the first wave (US, ID) to the data from the fifth wave.
- The assumption is that respondents stayed in their age group between the first and fifth wave (concerning US, ID).
- Where the age was given, they were grouped into the following categories:
    - 1: 16-24 years
    - 2: 25-34 years
    - 3: 35-44 years
    - 4: 45-54 years
    - 5: 55-64 years
    - 6: 65+ years
#### Flood experiences
- For the US and ID data, we check if they answered yes to experiencing flooding in any of the waves 1-5. We also want to get the year from the last flood experience. In W1, this is question Q18b_flood_year. In wave 2-4 it is R013_recent_flood_exp. If yes in
    - w2: apr-nov2020 --> 2020
    - w3: nov2020-may2021 --> 2021
    - w4: may-nov2021 --> 2021
    - w5: Nov2021 - Jul2023 --> 2022

In [8]:
US_data_w1 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_One_US.csv')
ID_data_w1 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_One_ID.csv')

US_data_w2_recontact = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Recontact_US.csv')
ID_data_w2_recontact = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Recontact_ID.csv')

US_data_w3 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Three_US.csv')
ID_data_w3 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Three_ID.csv')

US_data_w4 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Four_US.csv')
ID_data_w4 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Four_ID.csv')

# use only the columns needed for now
subset_US_data_w1 = US_data_w1[['ID', 'Q0_age', 'Q53_income_US', 'Q0_education_US', 'Q1_home_ID_NL_US', 'Q0_gender', 'Q18_flood_exp', 'Q18b_flood_year']]
subset_ID_data_w1 = ID_data_w1[['ID', 'Q0_age', 'Q53_income_ID', 'Q0_education_ID', 'Q1_home_ID_NL_US', 'Q0_gender', 'Q18_flood_exp', 'Q18b_flood_year']]

subset_w2_US = US_data_w2_recontact[['ID', 'R013_recent_flood_exp']]
subset_w2_ID = ID_data_w2_recontact[['ID', 'R013_recent_flood_exp']]

subset_w3_US = US_data_w3[['ID', 'R013_recent_flood_exp']]
subset_w3_ID = ID_data_w3[['ID', 'R013_recent_flood_exp']]

subset_w4_US = US_data_w3[['ID', 'R013_recent_flood_exp']]
subset_w4_ID = ID_data_w3[['ID', 'R013_recent_flood_exp']]

# add the country column
subset_US_data_w1['country'] = 'US'
subset_ID_data_w1['country'] = 'ID'
subset_w2_US['country'] = 'US'
subset_w2_ID['country'] = 'ID'
subset_w3_US['country'] = 'US'
subset_w3_ID['country'] = 'ID'
subset_w4_US['country'] = 'US'
subset_w4_ID['country'] = 'ID'

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_US_data_w1['country'] = 'US'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_ID_data_w1['country'] = 'ID'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w2_US['country'] = 'US'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w2_ID['country'] = 'ID'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w3_US['country'] = 'US'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w3_ID['country'] = 'ID'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w4_US['country'] = 'US'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/185215748.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_w4_ID['country'] = 'ID'

In [9]:
# combine the data of the different countries
data_w1_ID_US = pd.concat([subset_US_data_w1, subset_ID_data_w1], ignore_index = True)
data_w2_ID_US = pd.concat([subset_w2_US, subset_w2_ID], ignore_index = True)
data_w3_ID_US = pd.concat([subset_w3_US, subset_w3_ID], ignore_index = True)
data_w4_ID_US = pd.concat([subset_w4_US, subset_w4_ID], ignore_index = True)
data_w3_ID_US.head()

    ID  R013_recent_flood_exp country
0  259                      0      US
1  264                      0      US
2  267                      0      US
3  272                      0      US
4  273                      0      US

In [10]:
data_w2_ID_US = data_w2_ID_US.rename(columns={"R013_recent_flood_exp": "R013_recent_flood_exp_w2"})
data_w3_ID_US = data_w3_ID_US.rename(columns={"R013_recent_flood_exp": "R013_recent_flood_exp_w3"})
data_w4_ID_US = data_w4_ID_US.rename(columns={"R013_recent_flood_exp": "R013_recent_flood_exp_w4"})
data_w5 = data_w5.rename(columns={"R013_recent_flood_exp": "R013_recent_flood_exp_w5"})
data_w5 = data_w5.rename(columns={"Q18b_flood_year": "Q18b_flood_year_w5"})
data_w4_ID_US.head()

    ID  R013_recent_flood_exp_w4 country
0  259                         0      US
1  264                         0      US
2  267                         0      US
3  272                         0      US
4  273                         0      US

In [11]:
# mergin the data of the different waves
data_w5_w1 = pd.merge(data_w5, data_w1_ID_US,  on = ['ID', 'country'], how = 'left')
data_w5_earlier = pd.merge(data_w5_w1, data_w2_ID_US,  on = ['ID', 'country'], how = 'left')
data_w5_earlier = pd.merge(data_w5_earlier, data_w3_ID_US,  on = ['ID', 'country'], how = 'left')
data_w5_earlier = pd.merge(data_w5_earlier, data_w4_ID_US,  on = ['ID', 'country'], how = 'left')
data_w5_earlier.head()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q0_education_US,Q1_home_ID_NL_US,Q0_gender_y,Q18_flood_exp_y,Q18b_flood_year,Q53_income_ID,Q0_education_ID,R013_recent_flood_exp_w2,R013_recent_flood_exp_w3,R013_recent_flood_exp_w4
0,0,4.0,5.0,2.0,900000.0,2300.0,2022.0,4.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,5.0,2.0,600000.0,1200.0,1992.0,4.0,3.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,2.0,2.0,170000.0,900.0,2010.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2.0,2.0,1.0,NaN,1000.0,2021.0,2.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,97.0,4.0,2.0,350000.0,1500.0,2014.0,4.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data_w5_w1_grouping = data_w5_earlier[['ID', 'country', 
                                 'Q1_home_NL_UK', 'Q1_home_ID_NL_US',
                                 'Q53_income_ID', 'Q53_income_US', 'Q53_income_UK', 'Q53_income_NL',
                                 'Q0_education_UK', 'Q0_education_NL', 'Q0_education_US', 'Q0_education_ID',
                                 'Q0_age_x', 'Q0_age_y', 'Q0_gender_x', 'Q0_gender_y']]

### Connecting Income
1. Assigning income quintiles to ID responses.
2. Storing income quintiles in one column.

In [13]:
data_w5_w1_grouping.Q53_income_ID.describe()

count    2.150000e+02
mean     1.374147e+08
std      1.953469e+08
min      4.000000e+01
25%      4.200000e+07
50%      8.000000e+07
75%      1.500000e+08
max      2.000000e+09
Name: Q53_income_ID, dtype: float64

In [14]:
# assigning income quintiles to ID
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] > 51.1e+06,  'Q53_income_ID_q'] = 5
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] <= 51.1e+06,  'Q53_income_ID_q'] = 4
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] <= 35.8e+06,  'Q53_income_ID_q'] = 3
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] <= 26.6e+06,  'Q53_income_ID_q'] = 2
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] <= 19.4e+06,  'Q53_income_ID_q'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q53_income_ID'].isnull()) & (data_w5_w1_grouping['country'] == 'ID'),  'Q53_income_ID_q'] = 99

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/1165695013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping.loc[data_w5_w1_grouping['Q53_income_ID'] > 51.1e+06,  'Q53_income_ID_q'] = 5

In [15]:
data_w5_w1_grouping.groupby(['country', 'Q53_income_ID_q']).count()

                          ID  Q1_home_NL_UK  Q1_home_ID_NL_US  Q53_income_ID  \
country Q53_income_ID_q
ID      1.0               34              0                34             34
        2.0                5              0                 5              5
        3.0                7              0                 7              7
        4.0               27              0                27             27
        5.0              142              0               142            142
        99.0             125              0               125              0

                         Q53_income_US  Q53_income_UK  Q53_income_NL  \
country Q53_income_ID_q
ID      1.0                          0              0              0
        2.0                          0              0              0
        3.0                          0              0              0
        4.0                          0              0              0
        5.0                          0              0              0
        99.0                         0              0              0

                         Q0_education_UK  Q0_education_NL  Q0_education_US  \
country Q53_income_ID_q
ID      1.0                            0                0                0
        2.0                            0                0                0
        3.0                            0                0                0
        4.0                            0                0                0
        5.0                            0                0                0
        99.0                           0                0                0

                         Q0_education_ID  Q0_age_x  Q0_age_y  Q0_gender_x  \
country Q53_income_ID_q
ID      1.0                           34         0        34            0
        2.0                            5         0         5            0
        3.0                            7         0         7            0
        4.0                           27         0        27            0
        5.0                          142         0       142            0
        99.0                         125         0       125            0

                         Q0_gender_y
country Q53_income_ID_q
ID      1.0                       34
        2.0                        5
        3.0                        7
        4.0                       27
        5.0                      142
        99.0                     125

In [16]:
data_w5_w1_grouping['Q53_income_q'] = data_w5_w1_grouping['Q53_income_ID_q']

data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q53_income_US'].isnull() == False) & (data_w5_w1_grouping['country'] == 'US'),  'Q53_income_q'] = data_w5_w1_grouping['Q53_income_US']
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q53_income_UK'].isnull() == False) & (data_w5_w1_grouping['country'] == 'UK'),  'Q53_income_q'] = data_w5_w1_grouping['Q53_income_UK']
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q53_income_NL'].isnull() == False) & (data_w5_w1_grouping['country'] == 'NL'),  'Q53_income_q'] = data_w5_w1_grouping['Q53_income_NL']

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3920264143.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping['Q53_income_q'] = data_w5_w1_grouping['Q53_income_ID_q']

In [17]:
data_w5_w1_grouping.groupby(['country', 'Q53_income_q']).count()

                       ID  Q1_home_NL_UK  Q1_home_ID_NL_US  Q53_income_ID  \
country Q53_income_q
ID      1.0            34              0                34             34
        2.0             5              0                 5              5
        3.0             7              0                 7              7
        4.0            27              0                27             27
        5.0           142              0               142            142
        99.0          125              0               125              0
NL      1.0            50             50                 0              0
        2.0            47             47                 0              0
        3.0            29             29                 0              0
        4.0             8              8                 0              0
        5.0            15             15                 0              0
        99.0          269            269                 0              0
UK      1.0           109            109                 0              0
        2.0            84             84                 0              0
        3.0            98             98                 0              0
        4.0           121            121                 0              0
        5.0           191            191                 0              0
        99.0          138            138                 0              0
US      1.0            57              0                57              0
        2.0            73              0                73              0
        3.0           114              0               114              0
        4.0            80              0                80              0
        5.0            66              0                66              0
        99.0           58              0                58              0

                      Q53_income_US  Q53_income_UK  Q53_income_NL  \
country Q53_income_q
ID      1.0                       0              0              0
        2.0                       0              0              0
        3.0                       0              0              0
        4.0                       0              0              0
        5.0                       0              0              0
        99.0                      0              0              0
NL      1.0                       0              0             50
        2.0                       0              0             47
        3.0                       0              0             29
        4.0                       0              0              8
        5.0                       0              0             15
        99.0                      0              0            269
UK      1.0                       0            109              0
        2.0                       0             84              0
        3.0                       0             98              0
        4.0                       0            121              0
        5.0                       0            191              0
        99.0                      0            138              0
US      1.0                      57              0              0
        2.0                      73              0              0
        3.0                     114              0              0
        4.0                      80              0              0
        5.0                      66              0              0
        99.0                     58              0              0

                      Q0_education_UK  Q0_education_NL  Q0_education_US  \
country Q53_income_q
ID      1.0                         0                0                0
        2.0                         0                0                0
        3.0                         0                0                0
        4.0                         0                0                0
        5.0                         0                0                0
        99.0                        0                0                0
NL      1.0                         0               50                0
        2.0                         0               47                0
        3.0                         0               29                0
        4.0                         0                8                0
        5.0                         0               15                0
        99.0                        0              269                0
UK      1.0                       109                0                0
        2.0                        84                0                0
        3.0                        98                0                0
        4.0                       121                0                0
        5.0                       191                0                0
        99.0                      138                0                0
US      1.0                         0                0               57
        2.0                         0                0               73
        3.0                         0                0              114
        4.0                         0                0               80
        5.0                         0                0               66
        99.0                        0                0               58

                      Q0_education_ID  Q0_age_x  Q0_age_y  Q0_gender_x  \
country Q53_income_q
ID      1.0                        34         0        34            0
        2.0                         5         0         5            0
        3.0                         7         0         7            0
        4.0                        27         0        27            0
        5.0                       142         0       142            0
        99.0                      125         0       125            0
NL      1.0                         0        50         0           50
        2.0                         0        47         0           47
        3.0                         0        29         0           29
        4.0                         0         8         0            8
        5.0                         0        15         0           15
        99.0                        0       269         0          269
UK      1.0                         0       109         0          109
        2.0                         0        84         0           84
        3.0                         0        98         0           98
        4.0                         0       121         0          121
        5.0                         0       191         0          191
        99.0                        0       138         0          138
US      1.0                         0         0        57            0
        2.0                         0         0        73            0
        3.0                         0         0       114            0
        4.0                         0         0        80            0
        5.0                         0         0        66            0
        99.0                        0         0        58            0

                      Q0_gender_y  Q53_income_ID_q
country Q53_income_q
ID      1.0                    34               34
        2.0                     5                5
        3.0                     7                7
        4.0                    27               27
        5.0                   142              142
        99.0                  125              125
NL      1.0                     0                0
        2.0                     0                0
        3.0                     0                0
        4.0                     0                0
        5.0                     0                0
        99.0                    0                0
UK      1.0                     0                0
        2.0                     0                0
        3.0                     0                0
        4.0                     0                0
        5.0                     0                0
        99.0                    0                0
US      1.0                    57                0
        2.0                    73                0
        3.0                   114                0
        4.0                    80                0
        5.0                    66                0
        99.0                   58                0

### Connecting education
1. need to education to new education lables for all countries
2. Count occurances

In [18]:
# assigning education categories
#US
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 1),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 2),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 3),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 4),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 5),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 6),  'Q0_education_grouped'] = 4

#ID
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 1),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 2),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 3),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 4),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 5),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 6),  'Q0_education_grouped'] = 4
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_ID'] == 7),  'Q0_education_grouped'] = 4

#NL
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 1),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 2),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 3),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 4),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 5),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 6),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 7),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 8),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 9),  'Q0_education_grouped'] = 4
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_NL'] == 10),  'Q0_education_grouped'] = 4

#UK
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 1),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 2),  'Q0_education_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 3),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 4),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 5),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 6),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 7),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 8),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 9),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 10),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 11),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 12),  'Q0_education_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 13),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 14),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 15),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 16),  'Q0_education_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 17),  'Q0_education_grouped'] = 4
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_UK'] == 18),  'Q0_education_grouped'] = 4

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3204232599.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_education_US'] == 1),  'Q0_education_grouped'] = 1

In [19]:
data_w5_w1_grouping.loc[data_w5_w1_grouping['Q0_education_grouped'].isnull(),  'Q0_education_grouped'] = 98

In [20]:
data_w5_w1_grouping.groupby('Q0_education_grouped').count()

,ID,country,Q1_home_NL_UK,Q1_home_ID_NL_US,Q53_income_ID,Q53_income_US,Q53_income_UK,Q53_income_NL,Q0_education_UK,Q0_education_NL,Q0_education_US,Q0_education_ID,Q0_age_x,Q0_age_y,Q0_gender_x,Q0_gender_y,Q53_income_ID_q,Q53_income_q
Q0_education_grouped,,,,,,,,,,,,,,,,,,
1.0,59,59,55,4,0,4,27,28,27,28,4,0,55,4,55,4,0,59
2.0,641,641,400,241,58,140,249,151,249,151,140,101,400,241,400,241,101,641
3.0,829,829,419,410,142,195,242,177,242,177,195,215,419,410,419,410,215,829
4.0,396,396,263,133,15,109,201,62,201,62,109,24,263,133,263,133,24,396
98.0,22,22,22,0,0,0,22,0,22,0,0,0,22,0,22,0,0,22

In [21]:
data_w5_w1_grouping.groupby(['country', 'Q0_education_grouped']).count()

                               ID  Q1_home_NL_UK  Q1_home_ID_NL_US  \
country Q0_education_grouped
ID      2.0                   101              0               101
        3.0                   215              0               215
        4.0                    24              0                24
NL      1.0                    28             28                 0
        2.0                   151            151                 0
        3.0                   177            177                 0
        4.0                    62             62                 0
UK      1.0                    27             27                 0
        2.0                   249            249                 0
        3.0                   242            242                 0
        4.0                   201            201                 0
        98.0                   22             22                 0
US      1.0                     4              0                 4
        2.0                   140              0               140
        3.0                   195              0               195
        4.0                   109              0               109

                              Q53_income_ID  Q53_income_US  Q53_income_UK  \
country Q0_education_grouped
ID      2.0                              58              0              0
        3.0                             142              0              0
        4.0                              15              0              0
NL      1.0                               0              0              0
        2.0                               0              0              0
        3.0                               0              0              0
        4.0                               0              0              0
UK      1.0                               0              0             27
        2.0                               0              0            249
        3.0                               0              0            242
        4.0                               0              0            201
        98.0                              0              0             22
US      1.0                               0              4              0
        2.0                               0            140              0
        3.0                               0            195              0
        4.0                               0            109              0

                              Q53_income_NL  Q0_education_UK  Q0_education_NL  \
country Q0_education_grouped
ID      2.0                               0                0                0
        3.0                               0                0                0
        4.0                               0                0                0
NL      1.0                              28                0               28
        2.0                             151                0              151
        3.0                             177                0              177
        4.0                              62                0               62
UK      1.0                               0               27                0
        2.0                               0              249                0
        3.0                               0              242                0
        4.0                               0              201                0
        98.0                              0               22                0
US      1.0                               0                0                0
        2.0                               0                0                0
        3.0                               0                0                0
        4.0                               0                0                0

                              Q0_education_US  Q0_education_ID  Q0_age_x  \
country Q0_education_grouped
ID      2.0                                 0              101         0
        3.0                                 0              215         0
        4.0                                 0               24         0
NL      1.0                                 0                0        28
        2.0                                 0                0       151
        3.0                                 0                0       177
        4.0                                 0                0        62
UK      1.0                                 0                0        27
        2.0                                 0                0       249
        3.0                                 0                0       242
        4.0                                 0                0       201
        98.0                                0                0        22
US      1.0                                 4                0         0
        2.0                               140                0         0
        3.0                               195                0         0
        4.0                               109                0         0

                              Q0_age_y  Q0_gender_x  Q0_gender_y  \
country Q0_education_grouped
ID      2.0                        101            0          101
        3.0                        215            0          215
        4.0                         24            0           24
NL      1.0                          0           28            0
        2.0                          0          151            0
        3.0                          0          177            0
        4.0                          0           62            0
UK      1.0                          0           27            0
        2.0                          0          249            0
        3.0                          0          242            0
        4.0                          0          201            0
        98.0                         0           22            0
US      1.0                          4            0            4
        2.0                        140            0          140
        3.0                        195            0          195
        4.0                        109            0          109

                              Q53_income_ID_q  Q53_income_q
country Q0_education_grouped
ID      2.0                               101           101
        3.0                               215           215
        4.0                                24            24
NL      1.0                                 0            28
        2.0                                 0           151
        3.0                                 0           177
        4.0                                 0            62
UK      1.0                                 0            27
        2.0                                 0           249
        3.0                                 0           242
        4.0                                 0           201
        98.0                                0            22
US      1.0                                 0             4
        2.0                                 0           140
        3.0                                 0           195
        4.0                                 0           109

### Counting occurances of home type category
1. need align home type lables for all countries
2. Count occurances

In [22]:
# assigning education categories

data_w5_w1_grouping['Q1_home'] = data_w5_w1_grouping['Q1_home_ID_NL_US'] 

data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 1),  'Q1_home'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 2),  'Q1_home'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 3),  'Q1_home'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 4),  'Q1_home'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 5),  'Q1_home'] = 4
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q1_home_NL_UK'] == 6),  'Q1_home'] = 98

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/651987852.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping['Q1_home'] = data_w5_w1_grouping['Q1_home_ID_NL_US']

In [23]:
data_w5_w1_grouping.groupby('Q1_home').count()

,ID,country,Q1_home_NL_UK,Q1_home_ID_NL_US,Q53_income_ID,Q53_income_US,Q53_income_UK,Q53_income_NL,Q0_education_UK,Q0_education_NL,Q0_education_US,Q0_education_ID,Q0_age_x,Q0_age_y,Q0_gender_x,Q0_gender_y,Q53_income_ID_q,Q53_income_q,Q0_education_grouped
Q1_home,,,,,,,,,,,,,,,,,,,
1.0,541,541,426,115,16,93,196,230,196,230,93,22,426,115,426,115,22,541,541
2.0,517,517,339,178,88,44,287,52,287,52,44,134,339,178,339,178,134,517,517
3.0,674,674,236,438,95,288,210,26,210,26,288,150,236,438,236,438,150,674,674
4.0,23,23,5,18,2,15,4,1,4,1,15,3,5,18,5,18,3,23,23
97.0,39,39,0,39,14,8,0,0,0,0,8,31,0,39,0,39,31,39,39

In [24]:
data_w5_w1_grouping.groupby(['country', 'Q1_home']).count()

                  ID  Q1_home_NL_UK  Q1_home_ID_NL_US  Q53_income_ID  \
country Q1_home
ID      1.0       22              0                22             16
        2.0      134              0               134             88
        3.0      150              0               150             95
        4.0        3              0                 3              2
        97.0      31              0                31             14
NL      1.0      230            230                 0              0
        2.0       52             52                 0              0
        3.0       26             26                 0              0
        4.0        1              1                 0              0
UK      1.0      196            196                 0              0
        2.0      287            287                 0              0
        3.0      210            210                 0              0
        4.0        4              4                 0              0
US      1.0       93              0                93              0
        2.0       44              0                44              0
        3.0      288              0               288              0
        4.0       15              0                15              0
        97.0       8              0                 8              0

                 Q53_income_US  Q53_income_UK  Q53_income_NL  Q0_education_UK  \
country Q1_home
ID      1.0                  0              0              0                0
        2.0                  0              0              0                0
        3.0                  0              0              0                0
        4.0                  0              0              0                0
        97.0                 0              0              0                0
NL      1.0                  0              0            230                0
        2.0                  0              0             52                0
        3.0                  0              0             26                0
        4.0                  0              0              1                0
UK      1.0                  0            196              0              196
        2.0                  0            287              0              287
        3.0                  0            210              0              210
        4.0                  0              4              0                4
US      1.0                 93              0              0                0
        2.0                 44              0              0                0
        3.0                288              0              0                0
        4.0                 15              0              0                0
        97.0                 8              0              0                0

                 Q0_education_NL  Q0_education_US  Q0_education_ID  Q0_age_x  \
country Q1_home
ID      1.0                    0                0               22         0
        2.0                    0                0              134         0
        3.0                    0                0              150         0
        4.0                    0                0                3         0
        97.0                   0                0               31         0
NL      1.0                  230                0                0       230
        2.0                   52                0                0        52
        3.0                   26                0                0        26
        4.0                    1                0                0         1
UK      1.0                    0                0                0       196
        2.0                    0                0                0       287
        3.0                    0                0                0       210
        4.0                    0                0                0         4
US      1.0                    0               93                0         0
        2.0                    0               44                0         0
        3.0                    0              288                0         0
        4.0                    0               15                0         0
        97.0                   0                8                0         0

                 Q0_age_y  Q0_gender_x  Q0_gender_y  Q53_income_ID_q  \
country Q1_home
ID      1.0            22            0           22               22
        2.0           134            0          134              134
        3.0           150            0          150              150
        4.0             3            0            3                3
        97.0           31            0           31               31
NL      1.0             0          230            0                0
        2.0             0           52            0                0
        3.0             0           26            0                0
        4.0             0            1            0                0
UK      1.0             0          196            0                0
        2.0             0          287            0                0
        3.0             0          210            0                0
        4.0             0            4            0                0
US      1.0            93            0           93                0
        2.0            44            0           44                0
        3.0           288            0          288                0
        4.0            15            0           15                0
        97.0            8            0            8                0

                 Q53_income_q  Q0_education_grouped
country Q1_home
ID      1.0                22                    22
        2.0               134                   134
        3.0               150                   150
        4.0                 3                     3
        97.0               31                    31
NL      1.0               230                   230
        2.0                52                    52
        3.0                26                    26
        4.0                 1                     1
UK      1.0               196                   196
        2.0               287                   287
        3.0               210                   210
        4.0                 4                     4
US      1.0                93                    93
        2.0                44                    44
        3.0               288                   288
        4.0                15                    15
        97.0                8                     8

### Counting occurances of age category
1. need align age lables for all countries
2. Count occurances

In [25]:
# assigning age categories

data_w5_w1_grouping['Q0_age_grouped'] = data_w5_w1_grouping['Q0_age_y'] 

data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 16),  'Q0_age_grouped'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 25),  'Q0_age_grouped'] = 2
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 35),  'Q0_age_grouped'] = 3
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 45),  'Q0_age_grouped'] = 4
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 55),  'Q0_age_grouped'] = 5
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_age_x'] >= 65),  'Q0_age_grouped'] = 6

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/1035163871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping['Q0_age_grouped'] = data_w5_w1_grouping['Q0_age_y']

In [26]:
data_w5_w1_grouping.groupby('Q0_age_grouped').count()

,ID,country,Q1_home_NL_UK,Q1_home_ID_NL_US,Q53_income_ID,Q53_income_US,Q53_income_UK,Q53_income_NL,Q0_education_UK,Q0_education_NL,Q0_education_US,Q0_education_ID,Q0_age_x,Q0_age_y,Q0_gender_x,Q0_gender_y,Q53_income_ID_q,Q53_income_q,Q0_education_grouped,Q1_home
Q0_age_grouped,,,,,,,,,,,,,,,,,,,,
1.0,145,145,94,51,20,4,49,45,49,45,4,47,94,51,94,51,47,145,145,134
2.0,313,313,159,154,91,25,93,66,93,66,25,129,159,154,159,154,129,313,313,296
3.0,344,344,177,167,75,50,114,63,114,63,50,117,177,167,177,167,117,344,344,322
4.0,324,324,187,137,22,101,113,74,113,74,101,36,187,137,187,137,36,324,324,290
5.0,385,385,247,138,7,128,171,76,171,76,128,10,247,138,247,138,10,385,385,349
6.0,436,436,295,141,0,140,201,94,201,94,140,1,295,141,295,141,1,436,436,403

In [27]:
data_w5_w1_grouping.groupby(['country', 'Q0_age_grouped']).count()

                         ID  Q1_home_NL_UK  Q1_home_ID_NL_US  Q53_income_ID  \
country Q0_age_grouped
ID      1.0              47              0                47             20
        2.0             129              0               129             91
        3.0             117              0               117             75
        4.0              36              0                36             22
        5.0              10              0                10              7
        6.0               1              0                 1              0
NL      1.0              45             45                 0              0
        2.0              66             66                 0              0
        3.0              63             63                 0              0
        4.0              74             74                 0              0
        5.0              76             76                 0              0
        6.0              94             94                 0              0
UK      1.0              49             49                 0              0
        2.0              93             93                 0              0
        3.0             114            114                 0              0
        4.0             113            113                 0              0
        5.0             171            171                 0              0
        6.0             201            201                 0              0
US      1.0               4              0                 4              0
        2.0              25              0                25              0
        3.0              50              0                50              0
        4.0             101              0               101              0
        5.0             128              0               128              0
        6.0             140              0               140              0

                        Q53_income_US  Q53_income_UK  Q53_income_NL  \
country Q0_age_grouped
ID      1.0                         0              0              0
        2.0                         0              0              0
        3.0                         0              0              0
        4.0                         0              0              0
        5.0                         0              0              0
        6.0                         0              0              0
NL      1.0                         0              0             45
        2.0                         0              0             66
        3.0                         0              0             63
        4.0                         0              0             74
        5.0                         0              0             76
        6.0                         0              0             94
UK      1.0                         0             49              0
        2.0                         0             93              0
        3.0                         0            114              0
        4.0                         0            113              0
        5.0                         0            171              0
        6.0                         0            201              0
US      1.0                         4              0              0
        2.0                        25              0              0
        3.0                        50              0              0
        4.0                       101              0              0
        5.0                       128              0              0
        6.0                       140              0              0

                        Q0_education_UK  Q0_education_NL  Q0_education_US  \
country Q0_age_grouped
ID      1.0                           0                0                0
        2.0                           0                0                0
        3.0                           0                0                0
        4.0                           0                0                0
        5.0                           0                0                0
        6.0                           0                0                0
NL      1.0                           0               45                0
        2.0                           0               66                0
        3.0                           0               63                0
        4.0                           0               74                0
        5.0                           0               76                0
        6.0                           0               94                0
UK      1.0                          49                0                0
        2.0                          93                0                0
        3.0                         114                0                0
        4.0                         113                0                0
        5.0                         171                0                0
        6.0                         201                0                0
US      1.0                           0                0                4
        2.0                           0                0               25
        3.0                           0                0               50
        4.0                           0                0              101
        5.0                           0                0              128
        6.0                           0                0              140

                        Q0_education_ID  Q0_age_x  Q0_age_y  Q0_gender_x  \
country Q0_age_grouped
ID      1.0                          47         0        47            0
        2.0                         129         0       129            0
        3.0                         117         0       117            0
        4.0                          36         0        36            0
        5.0                          10         0        10            0
        6.0                           1         0         1            0
NL      1.0                           0        45         0           45
        2.0                           0        66         0           66
        3.0                           0        63         0           63
        4.0                           0        74         0           74
        5.0                           0        76         0           76
        6.0                           0        94         0           94
UK      1.0                           0        49         0           49
        2.0                           0        93         0           93
        3.0                           0       114         0          114
        4.0                           0       113         0          113
        5.0                           0       171         0          171
        6.0                           0       201         0          201
US      1.0                           0         0         4            0
        2.0                           0         0        25            0
        3.0                           0         0        50            0
        4.0                           0         0       101            0
        5.0                           0         0       128            0
        6.0                           0         0       140            0

                        Q0_gender_y  Q53_income_ID_q  Q53_income_q  \
country Q0_age_grouped
ID      1.0                      47               47            47
        2.0                     129              129           129
        3.0                     117              117           117
        4.0                      36               36            36
        5.0                      10               10            10
        6.0                       1                1             1
NL      1.0                       0                0            45
        2.0                       0                0            66
        3.0                       0                0            63
        4.0                       0                0            74
        5.0                       0                0            76
        6.0                       0                0            94
UK      1.0                       0                0            49
        2.0                       0                0            93
        3.0                       0                0           114
        4.0                       0                0           113
        5.0                       0                0           171
        6.0                       0                0           201
US      1.0                       4                0             4
        2.0                      25                0            25
        3.0                      50                0            50
        4.0                     101                0           101
        5.0                     128                0           128
        6.0                     140                0           140

                        Q0_education_grouped  Q1_home
country Q0_age_grouped
ID      1.0                               47       47
        2.0                              129      129
        3.0                              117      117
        4.0                               36       36
        5.0                               10       10
        6.0                                1        1
NL      1.0                               45       34
        2.0                               66       51
        3.0                               63       46
        4.0                               74       49
        5.0                               76       54
        6.0                               94       75
UK      1.0                               49       49
        2.0                               93       91
        3.0                              114      109
        4.0                              113      104
        5.0                              171      157
        6.0                              201      187
US      1.0                                4        4
        2.0                               25       25
        3.0                               50       50
        4.0                              101      101
        5.0                              128      128
        6.0                              140      140

### Counting occurances of gender category
1. need align age lables for all countries
2. Count occurances

In [28]:
data_w5_w1_grouping['Q0_gender_all'] = data_w5_w1_grouping['Q0_gender_x'] 

data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_gender_y'] == 1),  'Q0_gender_all'] = 1
data_w5_w1_grouping.loc[(data_w5_w1_grouping['Q0_gender_y'] == 2),  'Q0_gender_all'] = 2

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/2927714233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_w5_w1_grouping['Q0_gender_all'] = data_w5_w1_grouping['Q0_gender_x']

In [29]:
data_w5_w1_grouping.groupby('Q0_gender_all').count()

,ID,country,Q1_home_NL_UK,Q1_home_ID_NL_US,Q53_income_ID,Q53_income_US,Q53_income_UK,Q53_income_NL,Q0_education_UK,Q0_education_NL,...,Q0_education_ID,Q0_age_x,Q0_age_y,Q0_gender_x,Q0_gender_y,Q53_income_ID_q,Q53_income_q,Q0_education_grouped,Q1_home,Q0_age_grouped
Q0_gender_all,,,,,,,,,,,,,,,,,,,,,
1.0,925,925,530,395,119,208,332,198,332,198,...,187,530,395,530,395,187,925,925,849,925
2.0,870,870,477,393,96,240,392,85,392,85,...,153,477,393,477,393,153,870,870,822,870
3.0,4,4,4,0,0,0,1,3,1,3,...,0,4,0,4,0,0,4,4,4,4
4.0,9,9,9,0,0,0,0,9,0,9,...,0,9,0,9,0,0,9,9,9,9
5.0,18,18,18,0,0,0,5,13,5,13,...,0,18,0,18,0,0,18,18,18,18
99.0,121,121,121,0,0,0,11,110,11,110,...,0,121,0,121,0,0,121,121,92,121

In [30]:
data_w5_w1_grouping.groupby(['country', 'Q0_gender_all']).count()

                        ID  Q1_home_NL_UK  Q1_home_ID_NL_US  Q53_income_ID  \
country Q0_gender_all
ID      1.0            187              0               187            119
        2.0            153              0               153             96
NL      1.0            198            198                 0              0
        2.0             85             85                 0              0
        3.0              3              3                 0              0
        4.0              9              9                 0              0
        5.0             13             13                 0              0
        99.0           110            110                 0              0
UK      1.0            332            332                 0              0
        2.0            392            392                 0              0
        3.0              1              1                 0              0
        5.0              5              5                 0              0
        99.0            11             11                 0              0
US      1.0            208              0               208              0
        2.0            240              0               240              0

                       Q53_income_US  Q53_income_UK  Q53_income_NL  \
country Q0_gender_all
ID      1.0                        0              0              0
        2.0                        0              0              0
NL      1.0                        0              0            198
        2.0                        0              0             85
        3.0                        0              0              3
        4.0                        0              0              9
        5.0                        0              0             13
        99.0                       0              0            110
UK      1.0                        0            332              0
        2.0                        0            392              0
        3.0                        0              1              0
        5.0                        0              5              0
        99.0                       0             11              0
US      1.0                      208              0              0
        2.0                      240              0              0

                       Q0_education_UK  Q0_education_NL  Q0_education_US  \
country Q0_gender_all
ID      1.0                          0                0                0
        2.0                          0                0                0
NL      1.0                          0              198                0
        2.0                          0               85                0
        3.0                          0                3                0
        4.0                          0                9                0
        5.0                          0               13                0
        99.0                         0              110                0
UK      1.0                        332                0                0
        2.0                        392                0                0
        3.0                          1                0                0
        5.0                          5                0                0
        99.0                        11                0                0
US      1.0                          0                0              208
        2.0                          0                0              240

                       Q0_education_ID  Q0_age_x  Q0_age_y  Q0_gender_x  \
country Q0_gender_all
ID      1.0                        187         0       187            0
        2.0                        153         0       153            0
NL      1.0                          0       198         0          198
        2.0                          0        85         0           85
        3.0                          0         3         0            3
        4.0                          0         9         0            9
        5.0                          0        13         0           13
        99.0                         0       110         0          110
UK      1.0                          0       332         0          332
        2.0                          0       392         0          392
        3.0                          0         1         0            1
        5.0                          0         5         0            5
        99.0                         0        11         0           11
US      1.0                          0         0       208            0
        2.0                          0         0       240            0

                       Q0_gender_y  Q53_income_ID_q  Q53_income_q  \
country Q0_gender_all
ID      1.0                    187              187           187
        2.0                    153              153           153
NL      1.0                      0                0           198
        2.0                      0                0            85
        3.0                      0                0             3
        4.0                      0                0             9
        5.0                      0                0            13
        99.0                     0                0           110
UK      1.0                      0                0           332
        2.0                      0                0           392
        3.0                      0                0             1
        5.0                      0                0             5
        99.0                     0                0            11
US      1.0                    208                0           208
        2.0                    240                0           240

                       Q0_education_grouped  Q1_home  Q0_age_grouped
country Q0_gender_all
ID      1.0                             187      187             187
        2.0                             153      153             153
NL      1.0                             198      141             198
        2.0                              85       62              85
        3.0                               3        3               3
        4.0                               9        9               9
        5.0                              13       13              13
        99.0                            110       81             110
UK      1.0                             332      313             332
        2.0                             392      367             392
        3.0                               1        1               1
        5.0                               5        5               5
        99.0                             11       11              11
US      1.0                             208      208             208
        2.0                             240      240             240

### Tracing responses over numerous waves

#### Flood experience
Variable names:
- Wave 1: Q18_flood_experience
- Wave 2 (recontact), 3, 4: R013_recent flood exp
Flood year:
- Wave 1: Q18b_flood_year
- Wave 2 (recontact), 3, 4: R013_recent flood exp where w2: 2020, w3/4: 2021, w5: 2022

In [31]:
data_fl_exp = data_w5_earlier[['ID', 'country', 
                               'Q18_flood_exp_x', 'Q18_flood_exp_y', 
                               'Q18b_flood_year', 'Q18b_flood_year_w5',
                              'R013_recent_flood_exp_w5', 'R013_recent_flood_exp_w2', 
                              'R013_recent_flood_exp_w3', 'R013_recent_flood_exp_w4']]
data_fl_exp.describe()

,ID,Q18_flood_exp_x,Q18_flood_exp_y,Q18b_flood_year,Q18b_flood_year_w5,R013_recent_flood_exp_w5,R013_recent_flood_exp_w2,R013_recent_flood_exp_w3,R013_recent_flood_exp_w4
count,1947.000000,1159.000000,700.000000,290.000000,156.000000,788.000000,751.000000,788.000000,788.000000
mean,623.668207,0.134599,0.414286,2011.041379,2004.211538,0.157360,0.242344,0.295685,0.295685
std,543.680732,0.341442,0.492951,10.466870,19.242094,0.364372,0.428787,0.456640,0.456640
min,0.000000,0.000000,0.000000,1962.000000,1900.000000,0.000000,0.000000,0.000000,0.000000
25%,224.500000,0.000000,0.000000,2005.000000,1996.000000,0.000000,0.000000,0.000000,0.000000
50%,431.000000,0.000000,0.000000,2016.000000,2013.000000,0.000000,0.000000,0.000000,0.000000
75%,853.500000,0.000000,1.000000,2018.000000,2018.000000,0.000000,0.000000,1.000000,1.000000
max,2255.000000,1.000000,1.000000,2020.000000,2023.000000,1.000000,1.000000,1.000000,1.000000

In [32]:
# assign 1 to all that have experienced flood, replace leftover nans with 0 (no flood experience
data_fl_exp['Flood_exp_overall'] = data_fl_exp['Q18_flood_exp_x'] 

data_fl_exp.loc[(data_fl_exp['Q18_flood_exp_y'] == 1),  'Flood_exp_overall'] = 1
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w5'] == 1),  'Flood_exp_overall'] = 1
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w2'] == 1),  'Flood_exp_overall'] = 1
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w3'] == 1),  'Flood_exp_overall'] = 1
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w4'] == 1),  'Flood_exp_overall'] = 1

data_fl_exp['Flood_exp_overall'] = data_fl_exp['Flood_exp_overall'].fillna(0)

data_fl_exp.head()

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3003324686.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fl_exp['Flood_exp_overall'] = data_fl_exp['Q18_flood_exp_x']
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3003324686.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fl_exp['Flood_exp_overall'] = data_fl_exp['Flood_exp_overall'].fillna(0)

,ID,country,Q18_flood_exp_x,Q18_flood_exp_y,Q18b_flood_year,Q18b_flood_year_w5,R013_recent_flood_exp_w5,R013_recent_flood_exp_w2,R013_recent_flood_exp_w3,R013_recent_flood_exp_w4,Flood_exp_overall
0,0,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,1,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,3,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,4,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [33]:
# take the flood experience years given in w1 and w5
data_fl_exp['Last_flood_exp_year'] = np.where(
    ~data_fl_exp['Q18b_flood_year'].isna(),  
    data_fl_exp['Q18b_flood_year'],          
    data_fl_exp['Q18b_flood_year_w5']           
)

data_fl_exp.tail(10)

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3739378316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fl_exp['Last_flood_exp_year'] = np.where(

,ID,country,Q18_flood_exp_x,Q18_flood_exp_y,Q18b_flood_year,Q18b_flood_year_w5,R013_recent_flood_exp_w5,R013_recent_flood_exp_w2,R013_recent_flood_exp_w3,R013_recent_flood_exp_w4,Flood_exp_overall,Last_flood_exp_year
1937,2152,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1938,2157,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1939,2171,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1940,2241,US,NaN,1.0,1970.0,NaN,0.0,0.0,0.0,0.0,1.0,1970.0
1941,2244,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1942,2248,US,NaN,0.0,NaN,NaN,0.0,0.0,1.0,1.0,1.0,NaN
1943,2249,US,NaN,1.0,1964.0,NaN,0.0,0.0,0.0,0.0,1.0,1964.0
1944,2250,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1945,2253,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1946,2255,US,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN

In [34]:
# if they said they experienced flooding between the waves, take that as the year
# R013_recent flood exp where w2: 2020, w3/4: 2021, w5: 2022 

data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w5'] == 1),  'Last_flood_exp_year'] = 2022
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w2'] == 1),  'Last_flood_exp_year'] = 2020
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w3'] == 1),  'Last_flood_exp_year'] = 2021
data_fl_exp.loc[(data_fl_exp['R013_recent_flood_exp_w4'] == 1),  'Last_flood_exp_year'] = 2021

data_fl_exp['Last_flood_exp_year'] = data_fl_exp['Last_flood_exp_year'].fillna(0)

data_fl_exp.head()

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/4230975291.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fl_exp['Last_flood_exp_year'] = data_fl_exp['Last_flood_exp_year'].fillna(0)

,ID,country,Q18_flood_exp_x,Q18_flood_exp_y,Q18b_flood_year,Q18b_flood_year_w5,R013_recent_flood_exp_w5,R013_recent_flood_exp_w2,R013_recent_flood_exp_w3,R013_recent_flood_exp_w4,Flood_exp_overall,Last_flood_exp_year
0,0,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,1,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,2,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,3,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,4,NL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [35]:
data_fl_exp_red = data_fl_exp[['ID', 'country', 'Flood_exp_overall', 'Last_flood_exp_year']]

In [36]:
data_fl_exp_red.describe()

                ID  Flood_exp_overall  Last_flood_exp_year
count  1947.000000        1947.000000          1947.000000
mean    623.668207           0.325629           655.931176
std     543.680732           0.468730           944.215802
min       0.000000           0.000000             0.000000
25%     224.500000           0.000000             0.000000
50%     431.000000           0.000000             0.000000
75%     853.500000           1.000000          2013.000000
max    2255.000000           1.000000          2023.000000

## Reconnecting the newly grouped columns with the original dataframe

In [37]:
data_w5_w1_grouping_reduced = data_w5_w1_grouping[['ID', 'country', 'Q53_income_q', 'Q0_education_grouped', 'Q1_home', 'Q0_age_grouped', 'Q0_gender_all']]

In [38]:
data_w5_w1_grouping_reduced = data_w5_w1_grouping_reduced.fillna(98)

In [39]:
data_waves = pd.merge(data_w5_w1_grouping_reduced, data_fl_exp_red, on = ['ID', 'country'], how = 'left')
data_waves.head()

,ID,country,Q53_income_q,Q0_education_grouped,Q1_home,Q0_age_grouped,Q0_gender_all,Flood_exp_overall,Last_flood_exp_year
0,0,NL,99.0,2.0,3.0,4.0,1.0,0.0,0.0
1,1,NL,1.0,2.0,1.0,6.0,99.0,0.0,0.0
2,2,NL,99.0,2.0,1.0,5.0,1.0,0.0,0.0
3,3,NL,99.0,3.0,1.0,2.0,2.0,0.0,0.0
4,4,NL,99.0,3.0,98.0,4.0,1.0,0.0,0.0

In [40]:
data_joined = pd.merge(data_w5, data_waves, on=['ID', 'country'], how = 'left')
data_joined.head()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q29h_com_what_other_p5,Q29h_com_what_other_p6,Q29h_com_what_other_p7,Q53_income_q,Q0_education_grouped,Q1_home,Q0_age_grouped,Q0_gender_all,Flood_exp_overall,Last_flood_exp_year
0,0,4.0,5.0,2.0,900000.0,2300.0,2022.0,4.0,3.0,3.0,...,NaN,NaN,NaN,99.0,2.0,3.0,4.0,1.0,0.0,0.0
1,1,2.0,5.0,2.0,600000.0,1200.0,1992.0,4.0,3.0,4.0,...,NaN,NaN,NaN,1.0,2.0,1.0,6.0,99.0,0.0,0.0
2,2,2.0,2.0,2.0,170000.0,900.0,2010.0,3.0,2.0,3.0,...,NaN,NaN,NaN,99.0,2.0,1.0,5.0,1.0,0.0,0.0
3,3,2.0,2.0,1.0,NaN,1000.0,2021.0,2.0,4.0,1.0,...,NaN,NaN,NaN,99.0,3.0,1.0,2.0,2.0,0.0,0.0
4,4,97.0,4.0,2.0,350000.0,1500.0,2014.0,4.0,4.0,3.0,...,NaN,NaN,NaN,99.0,3.0,98.0,4.0,1.0,0.0,0.0

In [41]:
# put R03_perceived_damage, R03_perceived_damage_UK1, _UK2, _UK3 in one column
# no perceived damage for NL, therefore all labelled as 98 - don't know
data_joined['R03_perc_damage_all'] = data_joined['R03_perc_damage']

data_joined.loc[(data_joined['R03_perc_damage_UK1'].isnull() == False),  'R03_perc_damage_all'] = data_joined['R03_perc_damage_UK1']
data_joined.loc[(data_joined['R03_perc_damage_UK2'].isnull() == False),  'R03_perc_damage_all'] = data_joined['R03_perc_damage_UK2']
data_joined.loc[(data_joined['R03_perc_damage_UK3'].isnull() == False),  'R03_perc_damage_all'] = data_joined['R03_perc_damage_UK3']

data_joined.loc[(data_joined['R03_perc_damage_all'].isnull()),  'R03_perc_damage_all'] = 98 # don't know 

# if Q1_home empty, document it as "don't know"
data_joined.loc[(data_joined['Q1_home'].isnull()),  'Q1_home'] = 98 # don't know

# for the UK data, add areas
data_joined.loc[(data_joined['R03_perc_damage_UK1'].isnull() == False),  'Q0_area_UK'] = "Somerset"
data_joined.loc[(data_joined['R03_perc_damage_UK2'].isnull() == False),  'Q0_area_UK'] = "Norfolk/Suffolk"
data_joined.loc[(data_joined['R03_perc_damage_UK3'].isnull() == False),  'Q0_area_UK'] = "GreaterLondon"

data_joined.head()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q29h_com_what_other_p7,Q53_income_q,Q0_education_grouped,Q1_home,Q0_age_grouped,Q0_gender_all,Flood_exp_overall,Last_flood_exp_year,R03_perc_damage_all,Q0_area_UK
0,0,4.0,5.0,2.0,900000.0,2300.0,2022.0,4.0,3.0,3.0,...,NaN,99.0,2.0,3.0,4.0,1.0,0.0,0.0,98.0,NaN
1,1,2.0,5.0,2.0,600000.0,1200.0,1992.0,4.0,3.0,4.0,...,NaN,1.0,2.0,1.0,6.0,99.0,0.0,0.0,98.0,NaN
2,2,2.0,2.0,2.0,170000.0,900.0,2010.0,3.0,2.0,3.0,...,NaN,99.0,2.0,1.0,5.0,1.0,0.0,0.0,98.0,NaN
3,3,2.0,2.0,1.0,NaN,1000.0,2021.0,2.0,4.0,1.0,...,NaN,99.0,3.0,1.0,2.0,2.0,0.0,0.0,98.0,NaN
4,4,97.0,4.0,2.0,350000.0,1500.0,2014.0,4.0,4.0,3.0,...,NaN,99.0,3.0,98.0,4.0,1.0,0.0,0.0,98.0,NaN

In [42]:
# adding don't know column: if they answered don't know (98) for either perceived probability or perceived damage
# then their value is 1 in the perc_prob_dam_idk column. If they have an idea of their 
# flood probability or potential damage, their value is 0
data_joined['perc_prob_dam_idk'] = 0
data_joined.loc[(data_joined['R03_perc_damage_all'] == 98),  'perc_prob_dam_idk'] = 1
data_joined.loc[(data_joined['R02_perc_prob'] == 98),  'perc_prob_dam_idk'] = 1

data_joined['perc_prob_idk'] = 0
data_joined.loc[(data_joined['R02_perc_prob'] == 98),  'perc_prob_idk'] = 1

#adding the name_generator column - 1 when respondents filled NG, 0 when not
data_joined['name_generator'] = 0
data_joined.loc[data_joined['Q29a_adapt_p1'].isnull() == False, 'name_generator'] = 1
data_joined.head()

#"cleaning" the communication data
data_joined['Q27_fl_convo_people'] = data_joined['Q27_fl_convo_people'].fillna(0)
data_joined['Q25_fl_convo_times'] = data_joined['Q25_fl_convo_times'].fillna(0)

data_joined.describe()

,ID,Q1_home_NL_UK,Q4_home_size_NL,Q5_home_tenure,Q5b_home_sell,Q6_home_costs,Q7_move_in,Q8_move_out,Q12_neighborhood_trust,Q13_neighborhood_community,...,Q0_education_grouped,Q1_home,Q0_age_grouped,Q0_gender_all,Flood_exp_overall,Last_flood_exp_year,R03_perc_damage_all,perc_prob_dam_idk,perc_prob_idk,name_generator
count,1947.000000,1159.000000,418.000000,1159.000000,7.130000e+02,1.159000e+03,1159.000000,1159.000000,1159.000000,1159.000000,...,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000,1947.000000
mean,623.668207,15.153581,10.346890,5.176877,5.031729e+05,3.066496e+04,2008.633305,24.396894,3.616911,3.153581,...,3.887006,11.538778,3.923986,7.592193,0.325629,655.931176,34.550591,0.374936,0.096559,0.551618
std,543.680732,31.945315,24.871213,18.038070,9.429355e+05,7.229110e+05,13.519932,39.807454,1.017086,1.126177,...,10.094394,28.549877,1.605929,23.544236,0.468730,944.215802,45.355282,0.484231,0.295432,0.497456
min,0.000000,1.000000,1.000000,1.000000,0.000000e+00,0.000000e+00,1900.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,224.500000,2.000000,2.000000,1.000000,2.600000e+05,5.350000e+02,2001.000000,2.000000,3.000000,2.000000,...,2.000000,1.000000,3.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,431.000000,3.000000,3.000000,2.000000,3.800000e+05,9.500000e+02,2013.000000,4.000000,4.000000,3.000000,...,3.000000,2.000000,4.000000,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000
75%,853.500000,4.000000,5.000000,2.000000,5.250000e+05,1.500000e+03,2019.000000,4.000000,4.000000,4.000000,...,3.000000,3.000000,5.000000,2.000000,1.000000,2013.000000,98.000000,1.000000,0.000000,1.000000
max,2255.000000,97.000000,98.000000,97.000000,2.000000e+07,2.247238e+07,2023.000000,98.000000,5.000000,5.000000,...,98.000000,98.000000,6.000000,99.000000,1.000000,2023.000000,98.000000,1.000000,1.000000,1.000000

In [43]:
data_joined.to_csv('../data/processed/data_all_countries_w5_with_info_from_previous_waves.csv')

## Reducing it to the data used

In [44]:
data_respondents = pd.read_csv('../data/processed/data_all_countries_w5_with_info_from_previous_waves.csv')

#adding name generator column with the nr of names given
data_respondents['nr_ng_names'] = np.nan

data_respondents.loc[(data_respondents['Q29a_adapt_p1'].isnull() == True),  'nr_ng_names'] = 0
data_respondents.loc[(data_respondents['Q29a_adapt_p1'].isnull() == False),  'nr_ng_names'] = 1
data_respondents.loc[(data_respondents['Q29a_adapt_p2'].isnull() == False),  'nr_ng_names'] = 2
data_respondents.loc[(data_respondents['Q29a_adapt_p3'].isnull() == False),  'nr_ng_names'] = 3
data_respondents.loc[(data_respondents['Q29a_adapt_p4'].isnull() == False),  'nr_ng_names'] = 4
data_respondents.loc[(data_respondents['Q29a_adapt_p5'].isnull() == False),  'nr_ng_names'] = 5
data_respondents.loc[(data_respondents['Q29a_adapt_p6'].isnull() == False),  'nr_ng_names'] = 6
data_respondents.loc[(data_respondents['Q29a_adapt_p7'].isnull() == False),  'nr_ng_names'] = 7

In [45]:
# which variables we use to answer the questions
variables_used = ['country', 'ID', 
                  'name_generator', 'nr_ng_names', 'Q27_fl_convo_people', 'Q25_fl_convo_times',
                 'R02_perc_prob', 'R03_perc_damage_all', 'R05_worry', 'Flood_exp_overall', 'perc_prob_dam_idk', 'perc_prob_idk', 'Last_flood_exp_year',
                 'Q53_income_q', 'Q0_education_grouped', 'Q1_home', 'Q0_age_grouped', 'Q0_gender_all',
                 'Q28_convo_prob', 'Q28_convo_severity', 'Q28_convo_worry', 'Q28_convo_resp_efficacy', 
                  'Q28_convo_costs', 'Q28_convo_community', 'Q28_convo_gov']

In [46]:
# selection of subset of data
data_used = data_respondents[variables_used]
# not using ID data for this publication
data_used = data_used.loc[data_used['country'] != 'ID']
data_used.head()

,country,ID,name_generator,nr_ng_names,Q27_fl_convo_people,Q25_fl_convo_times,R02_perc_prob,R03_perc_damage_all,R05_worry,Flood_exp_overall,...,Q1_home,Q0_age_grouped,Q0_gender_all,Q28_convo_prob,Q28_convo_severity,Q28_convo_worry,Q28_convo_resp_efficacy,Q28_convo_costs,Q28_convo_community,Q28_convo_gov
0,NL,0,1,3.0,1.0,0,6,98.0,2,0.0,...,3.0,4.0,1.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0
1,NL,1,0,0.0,2.0,0,4,98.0,1,0.0,...,1.0,6.0,99.0,4.0,5.0,5.0,4.0,3.0,5.0,5.0
2,NL,2,0,0.0,0.0,0,2,98.0,1,0.0,...,1.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NL,3,0,0.0,0.0,0,1,98.0,1,0.0,...,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NL,4,1,3.0,0.0,0,2,98.0,1,0.0,...,98.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
data_used.country.value_counts()

country
UK    741
US    448
NL    418
Name: count, dtype: int64

In [48]:
data_used_98_removed = data_used[(data_used.R02_perc_prob != 95) &
                                 (data_used.R02_perc_prob != 98) & 
                                 (data_used.R02_perc_prob != 97) & 
                                 (data_used.R05_worry != 98) &
                                 (data_used.Q53_income_q != 99) &
                                 (data_used.Q0_education_grouped != 98) &
                                 (data_used.Q1_home != 97) &
                                 (data_used.Q1_home != 98) &
                                 (data_used.Q0_gender_all != 99)
                                ]
data_used_98_removed.describe()

,ID,name_generator,nr_ng_names,Q27_fl_convo_people,Q25_fl_convo_times,R02_perc_prob,R03_perc_damage_all,R05_worry,Flood_exp_overall,perc_prob_dam_idk,...,Q1_home,Q0_age_grouped,Q0_gender_all,Q28_convo_prob,Q28_convo_severity,Q28_convo_worry,Q28_convo_resp_efficacy,Q28_convo_costs,Q28_convo_community,Q28_convo_gov
count,923.000000,923.000000,923.000000,923.000000,923.000000,923.000000,923.000000,923.000000,923.000000,923.000000,...,923.000000,923.000000,923.000000,326.000000,326.000000,326.000000,326.000000,326.000000,326.000000,326.000000
mean,654.275190,0.533044,1.366197,1.985915,2.650054,2.721560,21.745395,1.686891,0.302275,0.204767,...,2.154930,4.300108,1.563380,3.220859,3.131902,3.269939,3.693252,3.834356,3.904908,3.478528
std,533.775612,0.499177,1.391103,7.117606,11.970407,2.159939,38.731446,0.950232,0.459493,0.403750,...,0.858064,1.501218,0.639484,1.031948,1.063128,1.087333,1.094497,1.082810,1.069942,1.178460
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,273.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,1.000000,3.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
50%,509.000000,1.000000,1.000000,0.000000,0.000000,2.000000,2.000000,1.000000,0.000000,0.000000,...,2.000000,5.000000,2.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000
75%,791.000000,1.000000,3.000000,2.000000,2.000000,4.000000,5.000000,2.000000,1.000000,0.000000,...,3.000000,6.000000,2.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,4.000000
max,2253.000000,1.000000,3.000000,100.000000,200.000000,9.000000,98.000000,5.000000,1.000000,1.000000,...,4.000000,6.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [49]:
data_used_98_removed.country.value_counts()

country
UK    509
US    335
NL     79
Name: count, dtype: int64

In [50]:
data_used.to_csv('../data/processed/data_p2_respondents.csv')
data_used_98_removed.to_csv('../data/processed/data_p2_respondents_98removed.csv')

## Preparing the NG data
Preparing the answers from the name generator questions.

In [51]:
ng_columns = ['ID', 'country',
              'Q29a_adapt_p1', 'Q29a_adapt_p2', 'Q29a_adapt_p3', 'Q29a_adapt_p4', 'Q29a_adapt_p5', 'Q29a_adapt_p6', 'Q29a_adapt_p7',
              'Q29b_who_family_p1', 'Q29b_who_family_p2', 'Q29b_who_family_p3', 'Q29b_who_family_p4', 'Q29b_who_family_p5','Q29b_who_family_p6', 'Q29b_who_family_p7',
              'Q29b_who_neighbor_p1', 'Q29b_who_neighbor_p2', 'Q29b_who_neighbor_p3', 'Q29b_who_neighbor_p4', 'Q29b_who_neighbor_p5', 'Q29b_who_neighbor_p6', 'Q29b_who_neighbor_p7', 
              'Q29b_who_colleague_p1', 'Q29b_who_colleague_p2', 'Q29b_who_colleague_p3', 'Q29b_who_colleague_p4', 'Q29b_who_colleague_p5', 'Q29b_who_colleague_p6', 'Q29b_who_colleague_p7', 
              'Q29b_who_online_p1', 'Q29b_who_online_p2', 'Q29b_who_online_p3', 'Q29b_who_online_p4', 'Q29b_who_online_p5', 'Q29b_who_online_p6', 'Q29b_who_online_p7', 
              'Q29b_who_gov_p1', 'Q29b_who_gov_p2', 'Q29b_who_gov_p3', 'Q29b_who_gov_p4', 'Q29b_who_gov_p5', 'Q29b_who_gov_p6', 'Q29b_who_gov_p7', 
              'Q29b_who_other_p1', 'Q29b_who_other_p2', 'Q29b_who_other_p3','Q29b_who_other_p4', 'Q29b_who_other_p5','Q29b_who_other_p6', 'Q29b_who_other_p7',
              'Q29c_similar_flood_p1', 'Q29c_similar_flood_p2', 'Q29c_similar_flood_p3', 'Q29c_similar_flood_p4', 'Q29c_similar_flood_p5', 'Q29c_similar_flood_p6', 'Q29c_similar_flood_p7',
              'Q29c_similar_house_p1', 'Q29c_similar_house_p2', 'Q29c_similar_house_p3',  'Q29c_similar_house_p4', 'Q29c_similar_house_p5',  'Q29c_similar_house_p6', 'Q29c_similar_house_p7', 
              'Q29c_similar_edu_p1', 'Q29c_similar_edu_p2', 'Q29c_similar_edu_p3',  'Q29c_similar_edu_p4', 'Q29c_similar_edu_p5',  'Q29c_similar_edu_p6', 'Q29c_similar_edu_p7', 
              'Q29c_similar_inc_p1', 'Q29c_similar_inc_p2', 'Q29c_similar_inc_p3', 'Q29c_similar_inc_p4', 'Q29c_similar_inc_p5', 'Q29c_similar_inc_p6', 'Q29c_similar_inc_p7', 
              'Q29c_similar_age_p1', 'Q29c_similar_age_p2', 'Q29c_similar_age_p3', 'Q29c_similar_age_p4', 'Q29c_similar_age_p5', 'Q29c_similar_age_p6', 'Q29c_similar_age_p7', 
              'Q29c_similar_none_p1', 'Q29c_similar_none_p2', 'Q29c_similar_none_p3', 'Q29c_similar_none_p4', 'Q29c_similar_none_p5', 'Q29c_similar_none_p6', 'Q29c_similar_none_p7', 
              'Q29d_distance_p1', 'Q29d_distance_p2', 'Q29d_distance_p3', 'Q29d_distance_p4', 'Q29d_distance_p5', 'Q29d_distance_p6', 'Q29d_distance_p7', 
              'Q29e_com_street_p1', 'Q29e_com_street_p2', 'Q29e_com_street_p3', 'Q29e_com_street_p4', 'Q29e_com_street_p5', 'Q29e_com_street_p6', 'Q29e_com_street_p7', 
              'Q29e_com_call_p1', 'Q29e_com_call_p2', 'Q29e_com_call_p3','Q29e_com_call_p4', 'Q29e_com_call_p5','Q29e_com_call_p6', 'Q29e_com_call_p7',
              'Q29e_com_gatherings_p1', 'Q29e_com_gatherings_p2', 'Q29e_com_gatherings_p3','Q29e_com_gatherings_p4', 'Q29e_com_gatherings_p5','Q29e_com_gatherings_p6', 'Q29e_com_gatherings_p7',
              'Q29e_com_work_p1', 'Q29e_com_work_p2', 'Q29e_com_work_p3', 'Q29e_com_work_p4', 'Q29e_com_work_p5', 'Q29e_com_work_p6', 'Q29e_com_work_p7', 
              'Q29e_com_other_p1', 'Q29e_com_other_p2', 'Q29e_com_other_p3', 'Q29e_com_other_p4', 'Q29e_com_other_p5', 'Q29e_com_other_p6', 'Q29e_com_other_p7', 
              'Q29f_com_freq_p1', 'Q29f_com_freq_p2', 'Q29f_com_freq_p3', 'Q29f_com_freq_p4', 'Q29f_com_freq_p5', 'Q29f_com_freq_p6', 'Q29f_com_freq_p7', 
              'Q29g_flood_com_freq_p1', 'Q29g_flood_com_freq_p2', 'Q29g_flood_com_freq_p3','Q29g_flood_com_freq_p4', 'Q29g_flood_com_freq_p5','Q29g_flood_com_freq_p6', 'Q29g_flood_com_freq_p7',
              'Q29h_com_what_cause_p1', 'Q29h_com_what_cause_p2', 'Q29h_com_what_cause_p3', 'Q29h_com_what_cause_p4', 'Q29h_com_what_cause_p5', 'Q29h_com_what_cause_p6', 'Q29h_com_what_cause_p7', 
              'Q29h_com_what_measures_p1', 'Q29h_com_what_measures_p2', 'Q29h_com_what_measures_p3', 'Q29h_com_what_measures_p4', 'Q29h_com_what_measures_p5', 'Q29h_com_what_measures_p6', 'Q29h_com_what_measures_p7', 
              'Q29h_com_what_community_p1', 'Q29h_com_what_community_p2', 'Q29h_com_what_community_p3', 'Q29h_com_what_community_p4', 'Q29h_com_what_community_p5', 'Q29h_com_what_community_p6', 'Q29h_com_what_community_p7', 
              'Q29h_com_what_gov_react_p1', 'Q29h_com_what_gov_react_p2', 'Q29h_com_what_gov_react_p3','Q29h_com_what_gov_react_p4', 'Q29h_com_what_gov_react_p5','Q29h_com_what_gov_react_p6', 'Q29h_com_what_gov_react_p7',
              'Q29h_com_what_gov_adapt_p1', 'Q29h_com_what_gov_adapt_p2', 'Q29h_com_what_gov_adapt_p3','Q29h_com_what_gov_adapt_p4', 'Q29h_com_what_gov_adapt_p5','Q29h_com_what_gov_adapt_p6', 'Q29h_com_what_gov_adapt_p7',
              'Q29h_com_what_livability_p1', 'Q29h_com_what_livability_p2', 'Q29h_com_what_livability_p3', 'Q29h_com_what_livability_p4', 'Q29h_com_what_livability_p5', 'Q29h_com_what_livability_p6', 'Q29h_com_what_livability_p7', 
              'Q29h_com_what_other_p1', 'Q29h_com_what_other_p2', 'Q29h_com_what_other_p3', 'Q29h_com_what_other_p4', 'Q29h_com_what_other_p5', 'Q29h_com_what_other_p6', 'Q29h_com_what_other_p7', 
              'Q29i_worry_p1', 'Q29i_worry_p2', 'Q29i_worry_p3', 'Q29i_worry_p4', 'Q29i_worry_p5', 'Q29i_worry_p6', 'Q29i_worry_p7',
              'Q29j_valuable_exp_p1', 'Q29j_valuable_exp_p2', 'Q29j_valuable_exp_p3', 'Q29j_valuable_exp_p4', 'Q29j_valuable_exp_p5', 'Q29j_valuable_exp_p6', 'Q29j_valuable_exp_p7',
             ]
other_columns = ['ID']
columns_to_make = ['country', 
                   'person']

In [52]:
NL_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Study_new_respondents_Wave_Five_NL.csv')
UK_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Study_new_respondents_Wave_Five_UK.csv')
US_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Five_US.csv')
ID_data_w5 = pd.read_csv('../data/SCALAR_Coastal_Longitudinal_Study_Wave_Five_ID.csv')


NL_data_w5 = NL_data_w5.replace(' ', np.NaN)
NL_data_w5 = NL_data_w5.replace('', np.NaN)
NL_data_w5 = NL_data_w5.apply(pd.to_numeric, errors='ignore')
NL_data_w5['country'] = 'NL'

UK_data_w5 = UK_data_w5.replace(' ', np.NaN)
UK_data_w5 = UK_data_w5.replace('', np.NaN)
UK_data_w5 = UK_data_w5.apply(pd.to_numeric, errors='ignore')
UK_data_w5['country'] = 'UK'

US_data_w5 = US_data_w5.replace(' ', np.NaN)
US_data_w5 = US_data_w5.replace('', np.NaN)
US_data_w5 = US_data_w5.apply(pd.to_numeric, errors='ignore')
US_data_w5['country'] = 'US'

ID_data_w5 = ID_data_w5.replace(' ', np.NaN)
ID_data_w5 = ID_data_w5.replace('', np.NaN)
ID_data_w5 = ID_data_w5.apply(pd.to_numeric, errors='ignore')
ID_data_w5['country'] = 'ID'

data_w5 = pd.concat([NL_data_w5, UK_data_w5, ID_data_w5, US_data_w5], ignore_index = True)

NG_data = data_w5[ng_columns]

print(NG_data.shape)
NG_data.head()

(1952, 212)

,ID,country,Q29a_adapt_p1,Q29a_adapt_p2,Q29a_adapt_p3,Q29a_adapt_p4,Q29a_adapt_p5,Q29a_adapt_p6,Q29a_adapt_p7,Q29b_who_family_p1,...,Q29i_worry_p5,Q29i_worry_p6,Q29i_worry_p7,Q29j_valuable_exp_p1,Q29j_valuable_exp_p2,Q29j_valuable_exp_p3,Q29j_valuable_exp_p4,Q29j_valuable_exp_p5,Q29j_valuable_exp_p6,Q29j_valuable_exp_p7
0,0,NL,1.0,0.0,98.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,3.0,3.0,3.0,NaN,NaN,NaN,NaN
1,1,NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NL,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,3.0,3.0,3.0,NaN,NaN,NaN,NaN

In [53]:
NG_data = NG_data.loc[NG_data['country'] != 'ID']
NG_data.shape

(1611, 212)

In [54]:
ng_df_rearranged = pd.DataFrame(columns = ['country',
                                           'ID',
                                           'person',
                                           'Q29a_adapt', 
                                           'Q29b_who_family', 'Q29b_who_neighbor', 'Q29b_who_colleague', 'Q29b_who_online', 'Q29b_who_gov', 'Q29b_who_other',
                                           'Q29c_similar_flood','Q29c_similar_house','Q29c_similar_edu', 'Q29c_similar_inc', 'Q29c_similar_age', 'Q29c_similar_none', 
                                           'Q29d_distance', 
                                           'Q29e_com_street', 'Q29e_com_call','Q29e_com_gatherings','Q29e_com_work', 'Q29e_com_other', 
                                           'Q29f_com_freq', 
                                           'Q29g_flood_com_freq',
                                           'Q29h_com_what_cause', 'Q29h_com_what_measures', 'Q29h_com_what_community', 'Q29h_com_what_gov_react','Q29h_com_what_gov_adapt',
                                           'Q29h_com_what_livability', 'Q29h_com_what_other', 
                                           'Q29i_worry',
                                           'Q29j_valuable_exp'
                                          ])
ng_df_rearranged

Empty DataFrame
Columns: [country, ID, person, Q29a_adapt, Q29b_who_family, Q29b_who_neighbor, Q29b_who_colleague, Q29b_who_online, Q29b_who_gov, Q29b_who_other, Q29c_similar_flood, Q29c_similar_house, Q29c_similar_edu, Q29c_similar_inc, Q29c_similar_age, Q29c_similar_none, Q29d_distance, Q29e_com_street, Q29e_com_call, Q29e_com_gatherings, Q29e_com_work, Q29e_com_other, Q29f_com_freq, Q29g_flood_com_freq, Q29h_com_what_cause, Q29h_com_what_measures, Q29h_com_what_community, Q29h_com_what_gov_react, Q29h_com_what_gov_adapt, Q29h_com_what_livability, Q29h_com_what_other, Q29i_worry, Q29j_valuable_exp]
Index: []

[0 rows x 33 columns]

In [55]:
# take ID from other dataframe    
ng_df_rearranged['ID'] = NG_data['ID']
ng_df_rearranged['country'] = NG_data['country']
# duplicate the rows as many names where given
ng_df_rearranged = ng_df_rearranged.loc[ng_df_rearranged.index.repeat(3)].reset_index(drop=True)
for i in range(len(ng_df_rearranged)):
    if i%3 ==0:
        ng_df_rearranged.iloc[i, 2] = 1 
    if i%3 ==1:
        ng_df_rearranged.iloc[i, 2] = 2
    if i%3 ==2:
        ng_df_rearranged.iloc[i, 2] = 3
ng_df_rearranged.head()

,country,ID,person,Q29a_adapt,Q29b_who_family,Q29b_who_neighbor,Q29b_who_colleague,Q29b_who_online,Q29b_who_gov,Q29b_who_other,...,Q29g_flood_com_freq,Q29h_com_what_cause,Q29h_com_what_measures,Q29h_com_what_community,Q29h_com_what_gov_react,Q29h_com_what_gov_adapt,Q29h_com_what_livability,Q29h_com_what_other,Q29i_worry,Q29j_valuable_exp
0,NL,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NL,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NL,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NL,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NL,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
columns_not_ng = ['ID', 'person', 'country'] # columns where no answers per name given
for column in ng_df_rearranged:
    if column not in columns_not_ng:
        #print(column)
        # getting column names for ng_df dataframe
        column_p1 = column + '_p1' 
        column_p2 = column + '_p2'
        column_p3 = column + '_p3'
        #print(column_p2)
        for country in NG_data.country.unique():
            for ID in NG_data.loc[NG_data['country'] == country].ID:
                #print(country, ID)
                # finding the corresponding value in the original dataset ng_df
                value_p1 = NG_data.loc[(NG_data['ID'] == ID) & (NG_data['country'] == country), [column_p1]].iloc[0][column_p1]
                value_p2 = NG_data.loc[(NG_data['ID'] == ID) & (NG_data['country'] == country), [column_p2]].iloc[0][column_p2]
                value_p3 = NG_data.loc[(NG_data['ID'] == ID) & (NG_data['country'] == country), [column_p3]].iloc[0][column_p3]
                #print(column, value_p1, value_p2, value_p3)
                ng_df_rearranged.loc[(ng_df_rearranged['ID'] == ID) & (ng_df_rearranged['country'] == country) & (ng_df_rearranged['person'] == 1), [column]] = value_p1
                ng_df_rearranged.loc[(ng_df_rearranged['ID'] == ID) & (ng_df_rearranged['country'] == country) & (ng_df_rearranged['person'] == 2), [column]] = value_p2
                ng_df_rearranged.loc[(ng_df_rearranged['ID'] == ID) & (ng_df_rearranged['country'] == country) & (ng_df_rearranged['person'] == 3), [column]] = value_p3
ng_df_rearranged.head()

,country,ID,person,Q29a_adapt,Q29b_who_family,Q29b_who_neighbor,Q29b_who_colleague,Q29b_who_online,Q29b_who_gov,Q29b_who_other,...,Q29g_flood_com_freq,Q29h_com_what_cause,Q29h_com_what_measures,Q29h_com_what_community,Q29h_com_what_gov_react,Q29h_com_what_gov_adapt,Q29h_com_what_livability,Q29h_com_what_other,Q29i_worry,Q29j_valuable_exp
0,NL,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,2.0,3.0
1,NL,0,2,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,3.0,3.0
2,NL,0,3,98.0,0.0,0.0,1.0,1.0,1.0,1.0,...,5.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,3.0,3.0
3,NL,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NL,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
# for unanswered questions, person value replaced with '-'
for i in range(len(ng_df_rearranged)):
   # print(ng_df_all.iloc[i][3])
    if ng_df_rearranged.iloc[i][3] == ' ' or ng_df_rearranged.iloc[i][3] == '' or np.isnan(ng_df_rearranged.iloc[i][3]):
        #print('empty slot found')
        ng_df_rearranged['person'][i] = '-'
# dropping duplicates (keeping only more than 1 entry per ID if actually multiple people answered
ng_df_all_red = ng_df_rearranged.drop_duplicates()

/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'
/var/folders/qn/rcpbyl8d6rs2ym4z26w2fk7wyq1ksg/T/ipykernel_57064/3112483928.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ng_df_rearranged['person'][i] = '-'

In [58]:
ng_df_all_red.shape

(3117, 33)

In [59]:
ng_df_all_red.head()

,country,ID,person,Q29a_adapt,Q29b_who_family,Q29b_who_neighbor,Q29b_who_colleague,Q29b_who_online,Q29b_who_gov,Q29b_who_other,...,Q29g_flood_com_freq,Q29h_com_what_cause,Q29h_com_what_measures,Q29h_com_what_community,Q29h_com_what_gov_react,Q29h_com_what_gov_adapt,Q29h_com_what_livability,Q29h_com_what_other,Q29i_worry,Q29j_valuable_exp
0,NL,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,2.0,3.0
1,NL,0,2,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,3.0,3.0
2,NL,0,3,98.0,0.0,0.0,1.0,1.0,1.0,1.0,...,5.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,3.0,3.0
3,NL,1,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NL,2,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
ng_df_all_red.to_csv('../data/processed/data_p2_NG_data.csv')